language: go
sudo: false
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - tip
os:
  - linux
  - osx
before_install:
  - go get github.com/golang/dep/...
  - go get github.com/tcnksm/ghr
install:
  - $GOPATH/bin/dep ensure
script:
  - make test
branches:
  only:
    - master
after_success:
  - make cross
  - ghr --username b4b4r07 --token $GITHUB_TOKEN --replace $(make version) dist/
